CinemaTicketsApp/Controllers/OrdersController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using CinemaTicketServices.Interface;
using DocumentFormat.OpenXml.Drawing;
using GemBox.Document;
using Microsoft.AspNetCore.Authorization;

namespace CinemaTicketsApp.Controllers {
    public class OrdersController : Controller {
        private readonly IOrderService _orderService;

        public OrdersController(IOrderService orderService) {
            _orderService = orderService;
            ComponentInfo.SetLicense("FREE-LIMITED-KEY");
        }

        // GET: Orders
        [Authorize]
        public IActionResult Index() {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(_orderService.GetAllOrdersForUser(userId));
        }
        

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateOrder() {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            _orderService.PlaceOrder(userId);
            return Redirect("Index");
        }

        public FileContentResult CreateOrderInvoice(Guid id) {
            var stream = _orderService.CreateOrderInvoice(id);
            return File(stream.ToArray(), new PdfSaveOptions().ContentType, "OrderInvoice.pdf");
        }

        [Authorize(Roles = "Admin")]
        public IActionResult ExportTickets() {
            return View(_orderService.GetUniqueGenres());
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public FileContentResult ExportTicketsByGenre(string genre) {
            string fileName = "Orders.xlsx";
            string contentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            var fileContent = _orderService.ExportToExcel(genre);

            return File(fileContent, contentType, fileName);
        }

        public IActionResult Checkout() {
            return View();
        }
    }
}

CinemaTicketsApp/Controllers/ShoppingCartController.cs
using System.Security.Claims;
using CinemaTicketServices.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CinemaTicketsApp.Controllers {
    public class ShoppingCartController : Controller {
        private readonly IShoppingCartService _shoppingCartService;

        public ShoppingCartController(IShoppingCartService shoppingCartService) {
            _shoppingCartService = shoppingCartService;
        }


        // GET: ShoppingCart
        [Authorize]
        public IActionResult Index() {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(_shoppingCartService.FetchShoppingCart(userId));
        }

        [HttpPost]
        [Authorize]
        public IActionResult AddToShoppingCart(Guid movieProjectionId, int quantity) {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            _shoppingCartService.AddTicketToShoppingCart(movieProjectionId, quantity, userId);
            return Redirect("Index");
        }

        public IActionResult DeleteItemFromShoppingCart(Guid movieProjectionId) {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            _shoppingCartService.RemoveTicketFromShoppingCart(movieProjectionId, userId);
            return Redirect("Index");
        }
    }
}

CinemaTicketsApp/Views/ShoppingCart/Details.cshtml
@model CinemaTicketsDomain.DomainModels.ShoppingCart

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>ShoppingCart</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomUser.Id)
        </dd>
    </dl>
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> | *@
    <a asp-action="Index">Back to List</a>
</div>

CinemaTicketsApp/Views/ShoppingCart/Index.cshtml
@using System.Diagnostics
@model CinemaTicketsDomain.DomainModels.ShoppingCart

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1 class="my-3">Shopping Cart</h1>
    <hr>

    <div class="d-flex align-items-start mt-2" style="gap: 25px">
        @foreach (var ticket in Model.Tickets) {
            <div class="card mb-3" style="width: 30%;">
                <img src="@ticket.MovieProjection.Movie.Image" class="card-img-top h-25" alt="@ticket.MovieProjection.Movie.Name">
                <div class="card-body">
                    <h5 class="card-title mt-2">@ticket.MovieProjection.Movie.Name</h5>
                    <hr>
                    <p class="card-text">Quantity: @ticket.Quantity</p>
                    <p class="card-text">Date: <b>@ticket.MovieProjection.DateTime</b></p>
                    <p class="card-text">Price for a single ticket: <b>$@ticket.MovieProjection.PriceOfTicket</b></p>
                    <a class="btn btn-danger" asp-controller="ShoppingCart" asp-action="DeleteItemFromShoppingCart" asp-route-movieProjectionId="@ticket.MovieProjectionId">Delete</a>
                </div>
            </div>
        }
    </div>

    <hr>

    @{
        float totalAmount = 0;
    }

    @foreach (var ticket in Model.Tickets) {
        float ticketAmount = ticket.MovieProjection.PriceOfTicket * ticket.Quantity;
        totalAmount += ticketAmount;
    }

    <!-- Display the total amount -->
    <div class="bg-light p-4 d-flex justify-content-between align-items-center">
        <h2 class="display-5">Total Amount: <b>$@totalAmount</b></h2>
        @if (Model.Tickets.Count > 0) {
            <a asp-controller="Orders" asp-action="Checkout" class="btn btn-success px-4 my-0">Order now!</a>
        }
        else {
            <a asp-controller="Orders" asp-action="Checkout" class="btn btn-success px-4 my-0 disabled">Order now!</a>
        }
    </div>
</div>